## Numpy Examples

In [20]:
### to install numpy 
!pip install numpy

In [21]:
import numpy as np
print('numpy successfully imported !')


numpy successfully imported !


### Numpy array creation method

In [22]:
lst = list(range(1,25))
arr1 = np.array(lst)
arr1
# creating first numpy array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [23]:
arr2 = np.arange(1,25)
arr2
# single dimension numpy array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [24]:
arr3 = np.array([1,2,3,4,5,6,7,8,9,4,5,6,1,2,3])
arr3
# single numpy array

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 4, 5, 6, 1, 2, 3])

In [25]:
arr4 = np.zeros((5,10))
arr4
# 2D Array with filling 0

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [26]:
arr5 = np.ones((10,5))
arr5
# 2D Array with filling 1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [27]:
arr6 = np.linspace(1,10,5)
arr6
# 1D Array in between 1 to  10,   5 elements

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [28]:
arr7 = np.arange(0,30).reshape(10,3)
arr7
# reshaping the array 1D to 2D

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

### random initialliazation array creation method

In [29]:
arr_1_D = np.random.randint(1,5,9)
arr_1_D
# Randomly initialization numpy array with integer filling value

array([2, 2, 4, 1, 4, 1, 4, 4, 3])

In [30]:
arr2D = np.random.randint(1,5,(5,2))
arr2D
#2D numpy array with filling random integer value

array([[1, 3],
       [1, 2],
       [1, 1],
       [1, 3],
       [4, 3]])

In [31]:
arr_1_D = np.random.random(10)
arr_1_D
# 1D Array ,it will fill floating value

array([0.65520637, 0.26044838, 0.71858341, 0.95858769, 0.94171036,
       0.22848227, 0.08688715, 0.96552868, 0.13394152, 0.43117082])

In [32]:
arr_2_D = np.random.random((5,10))
arr_2_D
#2D Array random initialization numpy array with floating value

array([[0.80621927, 0.60847073, 0.395852  , 0.60071533, 0.47805027,
        0.34175207, 0.21678268, 0.71347534, 0.59920144, 0.21433418],
       [0.22014533, 0.80122625, 0.73740129, 0.39190989, 0.75378015,
        0.39204034, 0.75064644, 0.59164273, 0.72881004, 0.45915411],
       [0.04099834, 0.82897525, 0.94958313, 0.0349612 , 0.9581746 ,
        0.2566487 , 0.34399207, 0.24590768, 0.42357002, 0.76913408],
       [0.62967636, 0.08770956, 0.64106409, 0.12478031, 0.70829179,
        0.43899673, 0.31107975, 0.95777733, 0.38935382, 0.49597971],
       [0.15908645, 0.34320658, 0.90312125, 0.90455552, 0.99673944,
        0.16850351, 0.70063595, 0.52383638, 0.93338879, 0.44723653]])

### Array attribute

In [33]:
arr = np.arange(60).reshape(12,5)
arr


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [34]:
arr.shape
# to check the shape of numpy array

(12, 5)

In [35]:
arr.dtype
# to check the data type of numpy array

dtype('int32')

In [36]:
arr.ndim
# to check the dimension of numpy array

2

In [37]:
arr.size     
# total no. of elements --> rows * columns


60

In [38]:
arr.flatten()    
# converting into  1D

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [39]:
arr.ravel()       
# converting 1 D

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [40]:
list_2D = [[1,2,3],[4,5,6]]
list_2D
# creating 2D python list

[[1, 2, 3], [4, 5, 6]]

In [41]:
arr = np.array(list_2D)
arr
# creating numpy array from python 2D list

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
arr.shape

(2, 3)

In [43]:
arr.T.shape        
 ## transposing the shape of the data

(3, 2)

# Acessing elements from array 1D and 2D array
<h2>For 1D array</h2>
<h2>[row_start:row_end:row_step]</h2><br>
<h2>For 2D array</h2>
<h2>[row_start:row_end:row_step,row_start:row_end:row_step]</h2>


### Dealing with 1D Array

In [44]:
arr = np.arange(60)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [45]:
arr[10]
# to access particular array

10

In [46]:
arr[0:5]
# to access particular group of items

array([0, 1, 2, 3, 4])

In [47]:
arr[0:20:2]
# access particular group of element with 1 jump

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### Dealing with 2D Array

In [48]:
arr = np.arange(60).reshape(12,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [49]:
arr[1]   
# to access particular row

array([5, 6, 7, 8, 9])

In [50]:
arr[1,1]  

# 1  --> for row
# 1  --> for column  
# to access particular element from particular row and column

6

In [51]:
arr[0:5,1:2]

# 0:5   --> for row
# 1:2   --> for column

array([[ 1],
       [ 6],
       [11],
       [16],
       [21]])

In [52]:
arr[1,3:5]
# sub elements from particular row and column

array([8, 9])

In [53]:
arr[7:8,4][0]=100
# manipulating the data of particular element in numpy array

### accessing last element by multiple way 

In [54]:
arr

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38, 100],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59]])

In [55]:
arr[11][-1]
# first way

59

In [56]:
arr[-1][-1]

59

In [57]:
arr[-1,-1]

59

In [58]:
arr[11:,-1][0]
# second way

59

In [59]:
arr[11,4]
# third way

59

In [60]:
arr

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38, 100],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59]])

In [61]:
arr[:,4][11]
# fourth way

59

In [62]:
arr[:,4][-1]


59

In [64]:
arr[4,2] = 500
# manipulatin the value by multiple way accessing

500

In [18]:
arr[10:,3:][1,1]


59

In [90]:
arr[10:,3:][1,1] = 500

In [91]:
arr[10:,3:][1,1]

500

## accessing elements from 3D Numpy Array

In [66]:
arr = np.array(np.arange(225).reshape(5,15,3))
arr

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [67]:
arr.shape
# now we got the 3D shape of numpy array
# 5  --> Tables
# 15 -- > Rows
# 3 -->  columns

(5, 15, 3)

In [15]:
print(f"dimension of array :- {arr.ndim}D")


dimension of array :- 3D


In [105]:
arr[0][2:]
# accessing rows from 0th tables

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

In [117]:
arr[:,0,:]  
# fetched first row from all the tables

array([[  0,   1,   2],
       [ 45,  46,  47],
       [ 90,  91,  92],
       [135, 136, 137],
       [180, 181, 182]])

In [120]:
arr[:,0:1,0:1]       
# only first element from all the tables

array([[[  0]],

       [[ 45]],

       [[ 90]],

       [[135]],

       [[180]]])

## replacing 100 to the 500 in 3D Numpy Array

In [125]:
arr[2][3][1]

# arr[2][3][1] = 500


100

In [131]:
arr[2,3,1]

100

In [130]:
arr[2:3,3:4,1:2]

array([[[100]]])

In [129]:
arr[2:3,3:4,1:2][0][0][0]

100

### To Reverse print all the elements

In [72]:
arr[0]
# we will reverse this first table of the 3D array 

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

In [75]:
arr[0][::-1]
# only row sequence has reversed

array([[42, 43, 44],
       [39, 40, 41],
       [36, 37, 38],
       [33, 34, 35],
       [30, 31, 32],
       [27, 28, 29],
       [24, 25, 26],
       [21, 22, 23],
       [18, 19, 20],
       [15, 16, 17],
       [12, 13, 14],
       [ 9, 10, 11],
       [ 6,  7,  8],
       [ 3,  4,  5],
       [ 0,  1,  2]])

In [76]:
arr[0][::-1,::-1]
# row and columns both are reversed

array([[44, 43, 42],
       [41, 40, 39],
       [38, 37, 36],
       [35, 34, 33],
       [32, 31, 30],
       [29, 28, 27],
       [26, 25, 24],
       [23, 22, 21],
       [20, 19, 18],
       [17, 16, 15],
       [14, 13, 12],
       [11, 10,  9],
       [ 8,  7,  6],
       [ 5,  4,  3],
       [ 2,  1,  0]])

In [78]:
arr[0] = arr[0][::-1,::-1]
# first table elements has been replaced with reversed elements

In [80]:
arr[0]

array([[44, 43, 42],
       [41, 40, 39],
       [38, 37, 36],
       [35, 34, 33],
       [32, 31, 30],
       [29, 28, 27],
       [26, 25, 24],
       [23, 22, 21],
       [20, 19, 18],
       [17, 16, 15],
       [14, 13, 12],
       [11, 10,  9],
       [ 8,  7,  6],
       [ 5,  4,  3],
       [ 2,  1,  0]])

### commonly used  function of Numpy array

In [88]:
arr = np.arange(60).reshape(15,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47],
       [48, 49, 50, 51],
       [52, 53, 54, 55],
       [56, 57, 58, 59]])

In [90]:
np.min(arr)

# same as min , max , mean ,sum , var , std
# minimum element from entire array
# you can also check for particualr row or column

0

In [104]:
print(f"16 is root of 4 :- {4**4}")
print(f"and square root of 16 will be :- {np.sqrt(16)}")
# sum of particualar row

16 is root of 4 :- 256
and square root of 16 will be :- 4.0


### SORTING IN NUMPY ARRAY

In [2]:
arr1 = np.array([2,5,4,1,3,6])
arr2 = np.array([[5,1,4,6,8],[1,7,8,6,4]])

In [3]:
arr1.sort()
arr1
## 1D sorted

array([1, 2, 3, 4, 5, 6])

In [4]:
arr1[::-1]
# now its sortecd in descending order

array([6, 5, 4, 3, 2, 1])

In [5]:
np.sort(arr2)
# 2D array sort in ascending order

array([[1, 4, 5, 6, 8],
       [1, 4, 6, 7, 8]])

In [8]:
arr2.sort()
arr2
# 2D array sort in ascending order

array([[1, 4, 5, 6, 8],
       [1, 4, 6, 7, 8]])

In [9]:
arr2[::-1,::-1]
# 2D array sort in descending order

array([[8, 7, 6, 4, 1],
       [8, 6, 5, 4, 1]])

### argsort()

In [10]:
arr1 = np.array([7,5,9])
arr1


array([7, 5, 9])

In [147]:
## argsort it returns sorted indexing

np.argsort(arr1)

array([1, 0, 2], dtype=int64)

In [149]:
arr2

array([[5, 1, 4, 6, 8],
       [1, 7, 8, 6, 4]])

In [152]:
np.argsort(arr2[0])

array([1, 2, 0, 3, 4], dtype=int64)

In [124]:
arr[::-1]

array([[56, 57, 58, 59],
       [52, 53, 54, 55],
       [48, 49, 50, 51],
       [44, 45, 46, 47],
       [40, 41, 42, 43],
       [36, 37, 38, 39],
       [32, 33, 34, 35],
       [28, 29, 30, 31],
       [24, 25, 26, 27],
       [20, 21, 22, 23],
       [16, 17, 18, 19],
       [12, 13, 14, 15],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

In [114]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47],
       [48, 49, 50, 51],
       [52, 53, 54, 55],
       [56, 57, 58, 59]])

# Arithmatical operation using Numpy array


In [83]:
a = [1,2,3,4,5,6,7,8,9]
b = [5,4,8,7,9,6,2,3,5]
ar1 = np.array(a)
ar2 = np.array(b)

### direct operation on element

In [84]:
ar1 + 2
# it will add 2 in each element of Array

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [136]:
ar1 * 2
# multiply in each element

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [137]:
ar1 - 1
# minus from each element

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [138]:
ar1 / 2
# dividing

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [146]:
ar1 + ar2
# array + array
# performed by the indexing
# array must in same shape to perform this operation

array([ 6,  6, 11, 11, 14, 12,  9, 11, 14])

## concatenate , vstack , hstack , split , hsplit , vsplit

In [148]:
np.concatenate([ar1,ar2])

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 5, 4, 8, 7, 9, 6, 2, 3, 5])

### Quizes on Numpy array

In [28]:
arr = np.arange(60).reshape(12,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

Function to manipulate a elements of last column in the 2D array by the range of row <br>
function should work on any no. of shape in 2D,

In [29]:
# defining function
def manipulation(arr):
    row , column = arr.shape
    arr[:,-1] = list(range(row))
    return arr

In [30]:
manipulate = manipulation(arr)
manipulate

array([[ 0,  1,  2,  3,  0],
       [ 5,  6,  7,  8,  1],
       [10, 11, 12, 13,  2],
       [15, 16, 17, 18,  3],
       [20, 21, 22, 23,  4],
       [25, 26, 27, 28,  5],
       [30, 31, 32, 33,  6],
       [35, 36, 37, 38,  7],
       [40, 41, 42, 43,  8],
       [45, 46, 47, 48,  9],
       [50, 51, 52, 53, 10],
       [55, 56, 57, 58, 11]])